### PR TITLE
Fixes bugs

### PR DESCRIPTION
**Pull request by wanderor**
- Only removes tabs created before last sync. This may explain why some people complained tabs being closed unexpectedly.
- Ignores hashcode part in URL. This may explain why some people complained about tabs being closed and recreated.
- Handles undefined values.
- Fixes checking of time_of_start.

### CODE REVIEW

**Comment by v-ko** [comment]
Thank you for the contribution, @wanderor ! I'll try to review the changes and do a release in the coming week.

**Comment by wanderor** [comment]
Thank you! Please hold the release for now. I saw several remaining issues, and am working on a more aggressive fix.

**Comment by v-ko** [comment]
That's great. I haven't been able to work on the extension for a while, and it was my first serious JS project, so I'm aware the code is quite messy. Do tell if you have any questions on it, I'll try to spare the time to support your work.

**Comment by wanderor** [comment]
Hi Petko, I committed a large revision after weeks of coding and testing. I think it is relatively stable now, verified in my complex network of 4 machines in 2 locations. Please take a look.

**Comment by v-ko** [comment]
Thank you so much for your work! A quick question, as I'm reviewing the code now - in this example: 
```
function initSettings(callback){
    let initVar = function( name, c ){
        settings[name].storage.get( name, function( data ){
            if( data[name] ){
                debug("[init]", name, ":", data[name]);
                settings[name].set( data[name]);
                if( c && typeof( c ) === "function" ){ c(); }
            }else{
                debug("[init]", name, ":", settings[name].defValue);
                setSetting( name, settings[name].defValue, false, c );
            }
        });
    };

    let initVars = function( names, c ){
        let name = names.shift();
        if( names.length > 0 ){
            initVar( name, function(){
                initVars( names, c );
            });
        }else{
            initVar( name, c );
        }
    };

    initVars( Object.keys( settings ), callback );
}
```
Why declare `initVar` in this manner (`let initVar = function( name, c ){`) and not just as a nested function, like `function initVar( name, c ){`. Is it just a style preference? Not that it matters much but I'm curious.

**Comment by v-ko** [comment]
And btw it's been quite some time since I've done major changes and tested, so I'm having problems installing the packed extension in Chrome (`CRX_REQUIRED_PROOF_MISSING`). And if I remember correctly - when loaded as unpacked - the extension can't use the Google Chrome sync API (testing confirms that). So how did you manage to test it? There's supposed to be an npm library to pack extensions in the CRX3 format, but that seems too hacky to be the only way.

**Comment by wanderor** [comment]
Hi Petko,

Yes, the embedded function looks clearer. I'll commit a refactoring CL to switch to that style. I'm mostly a C++ programmer, so unconsciously I adopted the C++ style:-)

In order to test a Chrome Extension at local machine via Chrome Extensions page -> “Load unpacked”, we need to generate a key:
    openssl genrsa 2048 | openssl pkcs8 -topk8 -nocrypt -out key.pem
    openssl rsa -in key.pem -pubout -outform DER | openssl base64 -A
    In manifest.json, add the generated key in format: “key”: “XXXX”
See: https://stackoverflow.com/questions/37317779/making-a-unique-extension-id-and-key-for-chrome-extension

**Comment by v-ko** [comment]
Thanks, that worked nicely :) From the tests I've done everything seems ok, so I'll ho ahead and publish the extension. I'll give you a mention in the extension description on the Web Store. If you want to take that off for some reason - contact me about that.

**Comment by v-ko** [comment]
By the way, I don't know how I overlooked that, but - why have you added host permissions for those?
```
    "http://*/*",
    "https://*/*"
```
I believe the extension doesn't make any requests that need them.

PS: I tried without them and figured out they're needed for the web requests API. Which if I've understood correctly from the code is for handling the login/redirect edge cases when syncing.
PS2: The extension is submitted for review. I was warned it would be a slower process because of the broader host permissions requested, but I couldn't figure out a way around that (e.g. using only 'activeTab' in some way), so we may have to wait a few weeks before 1.3.3 hits the store.

**Comment by petko10** [comment]
I tried without them and figured out they're needed for the web requests API. Which if I've understood correctly from the code is for handling the login/redirect edge cases when syncing.

**Comment by wanderor** [comment]
Thanks!

FYI, I identified and fixed another bug (introduced by my own code); will send another pull request, and will observe whether there are other bugs.

**Comment by v-ko** [comment]
Is it something serious? I think I can revert the version in the store if needed.

**Pull request merged**
