### PR TITLE
feature : pinned tabs

### PR DESCRIPTION
**Pull request by pwnorbitals**
First two commits : 

- Cleaning the code before making further changes - being able to select what you want to sync (keep pinned tabs pinned, sync only pinned tabs, and more)

- Applied the same formatting to the whole background.js file

- removed deprecated permission

No "real" code change for now

### CODE REVIEW

**Comment by v-ko** [comment]
Thanks for the time you're putting into the extension. Do tell if you need anything or at least when it's time for testing.

**Comment by pwnorbitals** [comment]
Thank you very much.
Here are the changes I plan to make in the next couple of commits : 
- keep the "pinned" status of the synced tabs
- be able to sync only pinned tabs

Testing will be needed when this work will be done :)

**Comment by pwnorbitals** [comment]
It would be great if we could start testing right now - could you also spend a tiny bit of time confirming the mistakes I "blindly" corrected as typos on "fixed typos causing errors" commit (mainly "|" replaced by "||", as "|" is a binary operator and I'm quite sure it wasn't used as such, but as a logical "or" operator) ?

Once testing is done on the current feature, I'll commit the other feature: keep the "pinned" status of pinned tabs.

Thanks :)

**Comment by v-ko** [comment]
Everything looks great. Your name is missing as a contributor btw (if you'd want that of course). We'll be testing without publishing to testers (since I have none) I guess ?

**Comment by pwnorbitals** [comment]
Well, first collaborative dev for me too - but I guess this is the way to go. I'll add myself as a contributor when the next feature will be done and everything will be tested. I have two computers to test for myself, so I'll do it, and if you also test on your configurations I think we'll be good to go.

**Comment by pwnorbitals** [comment]
I may put toggle switches (http://www.w3schools.com/howto/howto_css_switch.asp) instead of push buttons in the popup, do you have anything against it ?

**Comment by v-ko** [comment]
I'm cool with the toggle switches. I have two computers too, and I'll be testing tomorrow and the day after that (my exam's tomorrow morning).

**Comment by pwnorbitals** [comment]
do you know if this is accurate ?

```
StorageArea.set(object items, function callback) : items

An object which gives each key/value pair to update storage with. Any other key/value pairs in storage will not be affected.

Primitive values such as numbers will serialize as expected. Values with a typeof "object" and "function" will typically serialize to {}, with the exception of Array (serializes as expected), Date, and Regex (serialize using their String representation).

found here : https://developer.chrome.com/extensions/storage
```

Can we really not store objects in sync storage area ?

The way I would keep all the tabs pinned when they need to is create our own SyncData object containing an array of [tab URL + pinned status + other needed data (like if we want to keep them muted etc...)] and then serialize it (in JSON?) and push it to the sync storage as a string (or as an object directly if possible, which doesn't seem possible according the the above). What do you think?

Cheers,
Magix

(EDIT : according to http://stackoverflow.com/questions/3937000, it's actually possible ! )

**Comment by pwnorbitals** [comment]
While being stuck on adding features, I'm refactoring, debugging and testing. Feel free to test and report any bug / unexpected behaviour. Thanks ;-)

**Comment by v-ko** [comment]
Sorry for the delay, but I crossed M.D. off the bucket list, and went offline for a few days. 
So, the way you described storing the data seems ok. The algorithm for synchronization that currently applies the remote changes should work ok with that. I think at some point it would be cleaner to assign IDs to tabs (in order to track changes a bit more elegantly), but I'll get to that when we get to adding more features. I'll start testing now :)

**Comment by pwnorbitals** [comment]
No problem with you taking some time off, anyway that's all the point of open source project, you do it on your free time, no worries :)
Keep me updated !!

**Comment by v-ko** [comment]
Btw it's probably trivial, but I can't remember how testing is done without uploading the extension to the web store. Do you add a "key" to the manifest as is said here http://stackoverflow.com/questions/17958634/chrome-storage-sync-doesnt-sync-between-machines or do you pack the extension with a key.pem ?

**Comment by pwnorbitals** [comment]
for my part, I just download it (git clone / git pull) and import it as a developper on chrome (about://extensions, import unpacked extension) ;-)

**Comment by v-ko** [comment]
lol, nothing like that is needed, just the synchronization took a long time (and I thought it didn't work because some of the above magic hadn't been done).

**Comment by pwnorbitals** [comment]
haha, as long as it works... :)

**Comment by pwnorbitals** [comment]
If your test results are OK, please feel free to merge those 15 commits and update the extension on the store :) The next features will most likely take a bit of time to come as I now have more work for school, there is refactoring to do etc... :/ thanks !

**Comment by pwnorbitals** [comment]
Any updates on your testing ? :)

**Comment by v-ko** [comment]
Reviewed (most of) the code today, and testing is ok, so I'll merge, bump the version number, commit and upload to the store :)

**Comment by pwnorbitals** [comment]
Awesome, thanks !

**Pull request merged**
